### PR TITLE
Upgrade libgit2 version

### PR DESCRIPTION
**Pull request by rafeca**
This PR upgrades the version of `libgit2` used to the commit https://github.com/libgit2/libgit2/commit/9084712b555a876873bd7d7583f5befd47647c9d

This version contains the regression fix from https://github.com/libgit2/libgit2/pull/4809 which prevented `libgit2` to get upgraded and which we believe [will make Atom builds less flaky](https://github.com/atom/atom/issues/18990).

The reason why I haven't upgraded to latest `master` version is because I cannot manage to build `libgit2` with `node-gyp` with the changes in https://github.com/libgit2/libgit2/pull/4919: when applying these changes I get the following error message from `node-gyp`:

```
In file included from ../deps/libgit2/src/hash/hash_generic.c:8:
../deps/libgit2/src/hash/hash_generic.h:24:17: error: static declaration of 'git_hash_global_init' follows non-static declaration
GIT_INLINE(int) git_hash_global_init(void)
                ^
../deps/libgit2/src/hash.h:34:5: note: previous declaration is here
int git_hash_global_init(void);
```

I've been able to work around the error by moving the static declaration in https://github.com/libgit2/libgit2/blob/master/src/hash/hash_generic.h#L24-L27 to L12, but I'm not exactly familiar with C so I have no idea if this is a good solution :sweat_smile: /cc @pks-t

**Note**: This is a big upgrade: It includes `libgit2` changes from almost a year and [960 commits](https://github.com/libgit2/libgit2/compare/6311e886d8b5377c6037cd9937ccf66a71f3361d...9084712b555a876873bd7d7583f5befd47647c9d).

### CODE REVIEW

**Comment by rafeca** [comment]
Well this PR at the end seems to build fine 😓

If there's no opposition, tomorrow I'll merge it and release a new version of `git-utils` to try to integrate it as soon as possible into Atom.

I know that this is not ideal (since we're not pinning `libgit2` to a stable version), but this will at least give us early signal about whether upgrading `libgit2` fixes some of the Atom crashes.
